# Declaration {.unnumbered .unlisted}

I declare that this document is an original work of my own authorship and that it fulfills all the requirements of the Code of Conduct and Good Practices of the Universidade de Lisboa.

\par\vspace{2\baselineskip} 
\begingroup
\let\clearpage\relax
\let\cleardoublepage\relax

# Declaração {.unnumbered .unlisted}

Declaro que o presente documento é um trabalho original da minha autoria e que cumpre todos os  requisitos do Código de Conduta e Boas Práticas da Universidade de Lisboa.

\par\vspace{4\baselineskip} 

# AI Usage Disclosure {.unnumbered .unlisted}

I disclose that I have employed Artificial Intelligence (AI) tools to assist in the writing of this thesis. Namely, to gather papers for the literature review [@ai_elicit; @ai_scopus] and for textual and code review [@ai_copilot; @ai_chatgpt]. All content generated by these tools has been reviewed and edited by me to ensure accuracy and originality. I acknowledge the assistance provided by these tools while affirming that the intellectual content and analysis presented in this thesis are my own work.

\par\vspace{2\baselineskip} 

# Declaração Sobre Utilização de IA {.unnumbered .unlisted}

Declaro que utilizei ferramentas de Inteligência Artificial (IA) para auxiliar na elaboração desta dissertação. Nomeadamente, para a compilação de artigos para a revisão da literatura [@ai_elicit; @ai_scopus] e para a revisão textual e de código [@ai_copilot; @ai_chatgpt]. Todo o conteúdo gerado por estas ferramentas foi revisto e editado por mim de forma a garantir o seu rigor e originalidade. Reconheço o auxílio prestado por estas ferramentas, salvaguardando, no entanto, que o conteúdo intelectual e a análise apresentados nesta tese são da minha própria autoria.


<!-- https://libguides.princeton.edu/generativeAI/disclosure -->

\endgroup
\KOMAoptions{open=right}   
